spring.datasource.url=jdbc:mysql://localhost:3306/mylist?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=A14D06A10Allan##
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin