spring.datasource.url=jdbc:mysql://localhost:3306/mylist?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=A14D06A10Allan##
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
jwt.secret=e3a1c7f9d94328af02c4bd1e147b0fc6a9e78d4b83c55ea0749d12fb8beaa331
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG